### ISSUE TITLE
[1.19] Alchemist Immunity to bad potions error: Exception caught during firing event

### ISSUE THREAD

**Issue by jollyroger182** [DAQEM/JobsPlus-Archive#23]
I am using Minecraft 1.19, Forge 41.0.45, and Jobs+ 1.19-0.4.0 with JEI 11.0.0.206. When I bought the "Immune to bad potions" power-up and threw a splash poison at myself, this error occurred on the server and crashed it:

```text
[22:13:06] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: class me.daqem.jobsplus.events.PotionEvents$2 cannot be cast to class me.daqem.jobsplus.events.PotionEvents$3 (me.daqem.jobsplus.events.PotionEvents$2 and me.daqem.jobsplus.events.PotionEvents$3 are in module jobsplus@1.19-0.4.0 of loader 'TRANSFORMER' @71904469)
        Index: 2
        Listeners:
                0: NORMAL
                1: net.minecraftforge.eventbus.EventBus$$Lambda$4041/0x00000008015b2000@68ec7b16
                2: ASM: me.daqem.jobsplus.events.PotionEvents$2@25bb617 onTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
java.lang.ClassCastException: class me.daqem.jobsplus.events.PotionEvents$2 cannot be cast to class me.daqem.jobsplus.events.PotionEvents$3 (me.daqem.jobsplus.events.PotionEvents$2 and me.daqem.jobsplus.events.PotionEvents$3 are in module jobsplus@1.19-0.4.0 of loader 'TRANSFORMER' @71904469)
        at TRANSFORMER/jobsplus@1.19-0.4.0/me.daqem.jobsplus.events.___onTick_WorldTickEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:93)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at TRANSFORMER/forge@41.0.45/net.minecraftforge.event.ForgeEventFactory.onPostWorldTick(ForgeEventFactory.java:804)
        at TRANSFORMER/minecraft@1.19/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872)
        at TRANSFORMER/minecraft@1.19/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292)
        at TRANSFORMER/minecraft@1.19/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806)
        at TRANSFORMER/minecraft@1.19/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654)
        at TRANSFORMER/minecraft@1.19/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:245)
        at java.base/java.lang.Thread.run(Thread.java:833)

[22:13:06] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.ClassCastException: class me.daqem.jobsplus.events.PotionEvents$2 cannot be cast to class me.daqem.jobsplus.events.PotionEvents$3 (me.daqem.jobsplus.events.PotionEvents$2 and me.daqem.jobsplus.events.PotionEvents$3 are in module jobsplus@1.19-0.4.0 of loader 'TRANSFORMER' @71904469)
        at me.daqem.jobsplus.events.___onTick_WorldTickEvent.invoke(.dynamic) ~[jobsplus-1.19-0.4.0.jar%2399!/:1.19-0.4.0] {re:classloading,pl:eventbus:B}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:93) ~[eventbus-6.0.0.jar%2350!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%2350!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%2350!/:?] {}
        at net.minecraftforge.event.ForgeEventFactory.onPostWorldTick(ForgeEventFactory.java:804) ~[forge-1.19-41.0.45-universal.jar%23108!/:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.19-20220607.102129-srg.jar%23103!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19-20220607.102129-srg.jar%23103!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19-20220607.102129-srg.jar%23103!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19-20220607.102129-srg.jar%23103!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:245) ~[server-1.19-20220607.102129-srg.jar%23103!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at java.lang.Thread.run(Thread.java:833) [?:?] {}
```

Full crash report: [crash-2022-07-22_22.13.06-server.txt](https://github.com/DAQEM/JobsPlus/files/9168434/crash-2022-07-22_22.13.06-server.txt)

**Comment by DAQEM** [comment]
Fixed
