### ISSUE TITLE
Server Crashed when someone using Vein Mining Skill

### ISSUE THREAD

**Issue by GenjieHaruki** [DAQEM/JobsPlus-Archive#32]
java.lang.ClassCastException: class me.daqem.jobsplus.events.jobs.BuilderEvents$1 cannot be cast to class me.daqem.jobsplus.events.jobs.MinerEvents$1 (me.daqem.jobsplus.events.jobs.BuilderEvents$1 and me.daqem.jobsplus.events.jobs.MinerEvents$1 are in module jobsplus@1.19.1-0.5.1 of loader 'TRANSFORMER' @48eaf42f)
	at me.daqem.jobsplus.events.jobs.___onTick_LevelTickEvent.invoke(.dynamic) ~[jobsplus-1.19.1-0.5.1.jar%23137!/:1.19.1-0.5.1] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreLevelTick(ForgeEventFactory.java:804) ~[forge-1.19.2-43.1.32-universal.jar%23174!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:863) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.ServerSeedMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.server.DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.ServerSeedMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.ServerSeedMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.ServerSeedMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

**Comment by Zygus42** [comment]
This has just started happening on our server, but not just when using vein miner, also when placing blocks.  No idea why it just started happening, as we've been using this happily for quite some time.  It's crashing the server, which is more than just a nuisance.

Crash reports:
[crash-2022-10-16_22.40.57-server.txt](https://github.com/DAQEM/JobsPlus/files/9796975/crash-2022-10-16_22.40.57-server.txt)
[crash-2022-10-17_11.46.52-server.txt](https://github.com/DAQEM/JobsPlus/files/9796976/crash-2022-10-17_11.46.52-server.txt)
[crash-2022-10-17_12.42.42-server.txt](https://github.com/DAQEM/JobsPlus/files/9796977/crash-2022-10-17_12.42.42-server.txt)

Versions:
jobsplus-1.19.1-0.5.1
forge-1.19.2-43.1.25-installer

The only thing that I can think that changed recently is that I updated the server jvm arguments so as to do more garbage collection and clearance.

**Comment by DAQEM** [comment]
Fixed in the latest 1.19.2 version.
